### ISSUE TITLE
Technical Specifications and International Standards

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#28]
What makes then similar and what different, in terms of OWL properties and axioms, from Standards and [Technical Specifications](https://github.com/i40-Tools/StandardOntology/blob/65a6b662e754776bb39db85ef72515d18a1aa46d/sto.ttl#L553)?

**Comment by TasneemRashid** [comment]
Technical specification is different from a standard in the fact that it has not been passed through all the approval stages to be called a standard.

**Comment by igrangel** [comment]
Yes, agree, but how can this fact be represented in the ontology in terms of properties and axioms? For example, are the classes disjoint (owl:disjointWith), which properties they share and which they do not?

**Comment by PriyankaNanjappa** [comment]
`sto:TechnicalSpecification owl:disjointWith sto:Standard;`

**Comment by igrangel** [comment]
Can you provide a reason for supporting this design decision?

**Comment by PriyankaNanjappa** [comment]
Technical Specifications have the same attributes as a Standard does. In the IEC Webstore, one needs to look carefully what the publication type is otherwise you could easily not notice that it is a Technical Specification. In real world, this means that the Technical Specifications are yet to go through various approval stages to be called a Standard. The decision to introduce sto:TechnicalSpecification owl:disjointWith sto:Standard; relationship was to clarify the difference against the visual similarity in the way they are both represented in Webstore.

**Comment by sebbader** [comment]
I agree that they are sufficiantly different, nevertheless `sto:TechnicalSpecification owl:disjointWith sto:Standard;` is dangerous. Let's say:
`A a sto:TechnicalSpecification .
A sto:hasClassification x .`

leads to: 

`owl:Thing equals owl:Nothing .` because:

`sto:hasClassification rdfs:domain sto:Standard .`

I am not saying that we do not need the separation. But the properties are not (yet) modeled accordingly.

**Comment by sebbader** [comment]
A connected topic is the treatments of IETF RFCs (request for comment). While being a proposal in the original sense, RFCs are defacto standards. How do we want to model them? [example](https://github.com/i40-Tools/StandardOntology/blob/39b385ed46cbf110ee77104cf2fff82ea9f2c5b3/sto.ttl#L7848)
`sto:RFC_1122 rdf:type sto:Standard ;`
or 
`sto:RFC_1122 rdf:type sto:TechnicalSpecification;`

**Comment by PriyankaNanjappa** [comment]
About the
**sto:hasClassification rdfs:domain sto:Standard** 
We initially worked like this. The Properties we created had sto:Standard as its domain. But once we created the class [sto:Publication](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L199), this was an intermediate logical level between foaf:Document and [sto:Standard](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L759). [sto:TechnicalSpecification](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L793) and [sto:Standard](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L759) are both a [sto:Publication](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L199) type.

and the Domains of properties changed to sto:Publication, as in the example [sto:PublicationDate](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L467) or [sto:hasPublisher](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L321).

Please check if the Domain of sto:hasClassification can be changed to sto:Publication and it should solve the issue.

**Comment by PriyankaNanjappa** [comment]
About the RFCs. 
We could model as follows

sto:RFC_1122 rdf:type sto:Publication or sto:RFC_1122 rdf:type foaf:Document

Since they are neither Standards nor Technical Specification. They are a different Kind of Document. But still specifies information similar to standards. I would prefer for it to be sto:Publication  but, [sto:Publication ](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L749) as defined by [IEC-Publication](http://www.iec.ch/standardsdev/publications/?ref=menul) which is our reference ,talks only about International Standards,Technical Specifications,Publicly Available Specifications,Amendments,Technical Corrigenda, Interpretation Sheets,Technical Reports,Guides 
but not RFCs. I guess we could modify our sto:Publication to include RFCs and model them as Publications

**Comment by PriyankaNanjappa** [comment]
Please have a look at [this](https://github.com/i40-Tools/StandardOntology/commit/ace404944bcfdfcf4dbeec879ed44378f8b7c782) push. We distinguish Standards from specifications like this.

**Comment by sebbader** [comment]
In my view, RFCs fit into the definition of sto:Publication . You are right, IEC does not directly use the term 'RFC' but the further explanation perfectly fit. Therefore, let's put it one hierarchy level up and we are fine.

**Comment by sebbader** [comment]
If we do so, we definitly need to adjust the domain statements as you suggested [in your comment](https://github.com/i40-Tools/StandardOntology/issues/28#issuecomment-414255042)

**Comment by PriyankaNanjappa** [comment]
And this will be our [Technical Report](https://github.com/i40-Tools/StandardOntology/commit/ab61ba0eca7e5de4f380d222b628755a95766568). Another kind of Publication/Document

**Comment by PriyankaNanjappa** [comment]
If we agree on this,  we will make sure to update the definition of what a Publication means to us and make all the new kinds of Standard documents that we encounter further as a Publication type.
