### ISSUE TITLE
has Available Language for Standards

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#34]
We want to represent that the document for standard is in a certain language but dcterms:Language and dcterms:LinguisticSystem are dead ends. dcterms:Language just provides "Recommended best practice is to use a controlled vocabulary such as RFC 4646 [RFC4646]."

**Comment by igrangel** [comment]
This is an important decision that may lead us to create our own representation. Still, please have a look at the [LOV](http://lov.okfn.org/dataset/lov/) service, to search for something that can be useful for us.

**Comment by igrangel** [comment]
Please have a look at [this](http://www.lexvo.org/page/term/eng/Spanish) resource. In addition, check [this](https://www.w3.org/TR/prov-o/#hadPrimarySource) example. Here should be the answer to the languages of the documents of the standards.

**Comment by igrangel** [comment]
I have added [here](https://github.com/i40-Tools/StandardOntology/blob/7e40c074799c6f492b22bfba98299d4999744e04/sto.ttl#L2457) the proper way of adding languages. Please have a look and reproduce it properly.

**Comment by TasneemRashid** [comment]
@igrangel I have corrected the range of AvailableLanguage property. Please check if this issue can be closed.

**Comment by igrangel** [comment]
Please, check it [here](https://github.com/i40-Tools/StandardOntology/blob/88be7469b52f9f22d436edc1a63990cdef646971/sto.ttl#L3072) and [here](https://github.com/i40-Tools/StandardOntology/blob/88be7469b52f9f22d436edc1a63990cdef646971/sto.ttl#L4017) , and [here](https://github.com/i40-Tools/StandardOntology/blob/88be7469b52f9f22d436edc1a63990cdef646971/sto.ttl#L4086). I stopped, since I think you can easily check it further. Please let me know.

**Comment by PriyankaNanjappa** [comment]
We can close this issue.
