### ISSUE TITLE
Revising template for Standard instances

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#37]
The name of the instance should be shortened, Instead of [this](https://github.com/i40-Tools/StandardOntology/blob/1eff75ce08b8d53fa3caa02f684c0ee6d40db4e7/sto.ttl#L3203), having something like `IEC_60050`. 

More properties for the class [sto:TechnicalCommittee](https://github.com/i40-Tools/StandardOntology/blob/1eff75ce08b8d53fa3caa02f684c0ee6d40db4e7/sto.ttl#L609) should be added. 

Regarding `sto:hasEdition`, please have a look at https://github.com/i40-Tools/StandardOntology/issues/33

**Comment by PriyankaNanjappa** [comment]
The idea is to somehow distinguish between different versions of the standard. A standard can have 10 different versions developed over many decades. The property values will differ based on the version of the standard. I don't think we can create just a generic name (generic instance) since we loose out lot of relevant information. We can cut the name short but we might have to have our own convention to represent the version number in the instance name. [As this](https://webstore.iec.ch/publication/153) example shows, IEC 60038 has 10 other previous versions. This needs to be part of the Ontology too.

**Comment by igrangel** [comment]
But the version of the standards should not be annotated in this way. Rather, there should be a strategy to annotate the different versions of the standard. In terms of instances, they can even be considered different ones.

**Comment by PriyankaNanjappa** [comment]
We could delete a part of the name to make it short but this will be a problem when we try to search the standard on the webstore with the name. The string match fails while searching
Can we have the long name as in the webstore as the "rdfs:label" property of the standard? Atleast then the information is there somewhere in the data.

**Comment by igrangel** [comment]
The name should be short, this should not suppose a problem. The search can be done based on the `rdfs:label`. There you can use the long version of the name. If you need more, you can use `skos:altLabel` to complement the naming.

**Comment by PriyankaNanjappa** [comment]
Perfect! Then we don't have concerns going ahead. We will Keep the Standard number with just the year IEC_60050:1998 depicting that it was published in the same year and have longer version of the name in the rdfs:label. Thanks!

**Comment by igrangel** [comment]
No, the instance should read `sto:IEC_60050`, no more than that. In the `rdfs:label` you can complement the other value if needed.

**Comment by PriyankaNanjappa** [comment]
Can multiple instances with same name exist?

**Comment by igrangel** [comment]
Before answering, can you elaborate on one example where you need this?

**Comment by igrangel** [comment]
> 
> 
> Can multiple instances with same name exist?

No, this is a semantic error.
